### ISSUE TITLE
Something odd about compatible factorio version

### ISSUE THREAD

**Issue by Myricaulus** [trakos/CFAN#19]
Thanks for wanting to bring an issue to our attention!

**CFAN Version: 0.1.4

**Operating System: Win7

**The issue you are experiencing: The warehousing mod still gets displayed as only 0.15 compatible only, although on the factorio forum as well as in the info.json it clearly states its ready for 0.16. It shows the current correct version number of Warehousing as 0.1.0 but only 0.15 compatible . Refresh doesn't help. The mod was updated 4 days ago for 0.16. 

**How to recreate this issue:** 

**CFAN error codes (if applicable):**

**Comment by trakos** [comment]
It should be fixed now. That mod's info.json contained `"dependencies": ["base >= 0.15.0"]`, so cfan assumed it's for factorio 0.15. I've changed it so that it always uses field `factorio_version` instead (which indeed was 0.16.0).

**Comment by dgw** [comment]
Felt like adding (since I'm the one who left the base dependency at 0.15): The idea was for Factorio to allow loading the mod under either 0.15 or 0.16, since it should work in both. I've since learned that Factorio doesn't appear to have any way of making a single mod release compatible with multiple versions of the game, sadly.

Regardless, using the `factorio_version` field in all cases is much more robust for CFAN, since unlike the `base` dependency specification it's always required for mods built for 0.13+.
